---
- name: Fetch file from remote to local
  become: false # Using become may cause OOM errors. (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html#notes)
  ansible.builtin.fetch:
    src: "{{ nc_archive_path }}.{{ nextcloud_backup_format }}"
    dest: "{{ nextcloud_backup_fetch_local_path }}"
